
name: Deploy to Cloudways

on:
  push:
    branches: [ development ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa ${{ vars.SSH_HOST }} > ~/.ssh/known_hosts

    - name: RSync Deploy
      run: |
        sync_pairs=(
          "./themes/:${{ vars.SSH_FOLDER }}/themes/"
          "./mu-plugins/:${{ vars.SSH_FOLDER }}/mu-plugins/"
        )

        for pair in "${sync_pairs[@]}"; do
          IFS=":" read -r local_path remote_path <<< "$pair"
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" \
            "$local_path" ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }}:"$remote_path"
        done